//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "Цена as \'Цена\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Статус as \'Статус\'",
            "Кладовщик as \'Кладовщик\'",
            "Кладовщик.Отчество as \'Отчество\'"}, Hidden=new string[] {
            "Кладовщик.Отчество"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "Кладовщик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Отчество")]
    [View("ЗаказL", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "Цена as \'Цена\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Статус as \'Статус\'",
            "Кладовщик.Отчество as \'Отчество\'"})]
    public class Заказ : IIS.Sklad2.Документ
    {
        
        private System.DateTime fДатаОплаты;
        
        private double fЦена;
        
        private System.DateTime fДатаОтгрузки;
        
        private string fСтатус;
        
        private IIS.Sklad2.Сотрудник fКладовщик;
        
        private IIS.Sklad2.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get start)
                System.DateTime result = this.fДатаОтгрузки;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set start)
                this.fДатаОтгрузки = value;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        [StrLen(255)]
        public virtual string Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                string result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Цена CustomAttributes)

        // *** End programmer edit section *** (Заказ.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Цена Get start)

                // *** End programmer edit section *** (Заказ.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Заказ.Цена Get end)

                // *** End programmer edit section *** (Заказ.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Цена Set start)

                // *** End programmer edit section *** (Заказ.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Заказ.Цена Set end)

                // *** End programmer edit section *** (Заказ.Цена Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Кладовщик CustomAttributes)

        // *** End programmer edit section *** (Заказ.Кладовщик CustomAttributes)
        [PropertyStorage(new string[] {
                "Кладовщик"})]
        [NotNull()]
        public virtual IIS.Sklad2.Сотрудник Кладовщик
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Кладовщик Get start)

                // *** End programmer edit section *** (Заказ.Кладовщик Get start)
                IIS.Sklad2.Сотрудник result = this.fКладовщик;
                // *** Start programmer edit section *** (Заказ.Кладовщик Get end)

                // *** End programmer edit section *** (Заказ.Кладовщик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Кладовщик Set start)

                // *** End programmer edit section *** (Заказ.Кладовщик Set start)
                this.fКладовщик = value;
                // *** Start programmer edit section *** (Заказ.Кладовщик Set end)

                // *** End programmer edit section *** (Заказ.Кладовщик Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.Sklad2.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.Sklad2.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.Sklad2.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Sklad2.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Sklad2.Заказ));
                }
            }
        }
    }
}
