//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Sklad2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состоние заказа.
    /// </summary>
    // *** Start programmer edit section *** (СостониеЗаказа CustomAttributes)

    // *** End programmer edit section *** (СостониеЗаказа CustomAttributes)
    public enum СостониеЗаказа
    {
        
        // *** Start programmer edit section *** (СостониеЗаказа.Оплаченный CustomAttributes)

        // *** End programmer edit section *** (СостониеЗаказа.Оплаченный CustomAttributes)
        Оплаченный,
        
        // *** Start programmer edit section *** (СостониеЗаказа.Новый CustomAttributes)

        // *** End programmer edit section *** (СостониеЗаказа.Новый CustomAttributes)
        Новый,
        
        // *** Start programmer edit section *** (СостониеЗаказа.Отмененный CustomAttributes)

        // *** End programmer edit section *** (СостониеЗаказа.Отмененный CustomAttributes)
        Отмененный,
    }
}
